import type { ConformanceTestDefinition } from "./conformance-test";

export const CONFORMANCE_TESTS: readonly ConformanceTestDefinition[] = [
  {
    test_id: "AOS-CONTRACT-001",
    family: "Contract conformance",
    requirement_reference: "CONFORMANCE-01",
    mode: "STATIC",
    preconditions: ["Canonical implementation schema is available"],
    inputs: ["CapabilityContract", "InterfaceContract", "ImplementationProfile"],
    expected_behavior: ["Required semantic contract fields are represented"],
    evidence_requirements: ["Source contract references", "Validation result"],
    validation_criteria: ["No required contract field is silently omitted"],
    provider_neutral: true,
  },
  {
    test_id: "AOS-INTERFACE-001",
    family: "Interface conformance",
    requirement_reference: "CONFORMANCE-02",
    mode: "STATIC",
    preconditions: ["Interface contract is available"],
    inputs: ["InterfaceContract"],
    expected_behavior: ["Request, response, state, idempotency and recovery semantics are represented"],
    evidence_requirements: ["Interface source reference", "Validation result"],
    validation_criteria: ["Interface semantics remain provider-neutral"],
    provider_neutral: true,
  },
  {
    test_id: "AOS-GOVERNANCE-001",
    family: "Governance/authorization conformance",
    requirement_reference: "CONFORMANCE-03",
    mode: "RUNTIME",
    preconditions: ["Authorized runtime boundary exists"],
    inputs: ["Authorization reference", "Execution request"],
    expected_behavior: ["Execution cannot bypass authorization"],
    evidence_requirements: ["Authorization evidence", "Execution evidence"],
    validation_criteria: ["Unauthorized execution is rejected or blocked"],
    provider_neutral: true,
  },
  {
    test_id: "AOS-STATE-001",
    family: "State-transition conformance",
    requirement_reference: "CONFORMANCE-04",
    mode: "RUNTIME",
    preconditions: ["State transition model is bound"],
    inputs: ["Execution request", "Expected state transitions"],
    expected_behavior: ["Observed states follow the declared transition model"],
    evidence_requirements: ["Execution trace", "State evidence"],
    validation_criteria: ["No undeclared transition is accepted"],
    provider_neutral: true,
  },
  {
    test_id: "AOS-EVIDENCE-001",
    family: "Evidence/provenance conformance",
    requirement_reference: "CONFORMANCE-05",
    mode: "RUNTIME",
    preconditions: ["Evidence contract is available"],
    inputs: ["Execution observation"],
    expected_behavior: ["Evidence has source, provenance, timestamp and validation linkage"],
    evidence_requirements: ["EvidenceRecord"],
    validation_criteria: ["Evidence is traceable to its source"],
    provider_neutral: true,
  },
  {
    test_id: "AOS-FAILURE-001",
    family: "Failure-state conformance",
    requirement_reference: "CONFORMANCE-06",
    mode: "RUNTIME",
    preconditions: ["Controlled failure injection is available"],
    inputs: ["Failure scenario"],
    expected_behavior: ["Failure is represented as an explicit governed state"],
    evidence_requirements: ["Failure evidence", "Execution record"],
    validation_criteria: ["Failure is not silently converted to success"],
    provider_neutral: true,
  },
  {
    test_id: "AOS-RECOVERY-001",
    family: "Recovery/retry conformance",
    requirement_reference: "CONFORMANCE-07",
    mode: "RUNTIME",
    preconditions: ["Failure-state test is available"],
    inputs: ["Recoverable failure scenario"],
    expected_behavior: ["Recovery/retry follows declared policy"],
    evidence_requirements: ["Retry evidence", "Trace"],
    validation_criteria: ["Recovery is observable and bounded"],
    provider_neutral: true,
  },
  {
    test_id: "AOS-IDEMPOTENCY-001",
    family: "Idempotency conformance",
    requirement_reference: "CONFORMANCE-08",
    mode: "RUNTIME",
    preconditions: ["Idempotency contract is available"],
    inputs: ["Repeated equivalent request"],
    expected_behavior: ["Repeated execution does not create an invalid duplicate effect"],
    evidence_requirements: ["Execution records", "State/result evidence"],
    validation_criteria: ["Duplicate behavior matches contract"],
    provider_neutral: true,
  },
  {
    test_id: "AOS-SUBSTITUTION-001",
    family: "Provider substitution conformance",
    requirement_reference: "CONFORMANCE-09",
    mode: "RUNTIME",
    preconditions: ["At least two conforming provider implementations exist"],
    inputs: ["Equivalent capability request"],
    expected_behavior: ["Capability semantics remain stable across providers"],
    evidence_requirements: ["Provider binding records", "Comparative evidence"],
    validation_criteria: ["Provider-specific behavior does not redefine capability semantics"],
    provider_neutral: true,
  },
  {
    test_id: "AOS-SECURITY-001",
    family: "Security-boundary conformance",
    requirement_reference: "CONFORMANCE-10",
    mode: "RUNTIME",
    preconditions: ["Authorized security test boundary exists"],
    inputs: ["Authorized security test scenarios"],
    expected_behavior: ["Security boundary rejects unauthorized access without weakening controls"],
    evidence_requirements: ["Security evidence", "Trace"],
    validation_criteria: ["No secret exposure or security downgrade"],
    provider_neutral: true,
  },
  {
    test_id: "AOS-OBSERVABILITY-001",
    family: "Observability/traceability conformance",
    requirement_reference: "CONFORMANCE-11",
    mode: "RUNTIME",
    preconditions: ["Trace/evidence collection is available"],
    inputs: ["Execution request"],
    expected_behavior: ["Execution is traceable from request through result"],
    evidence_requirements: ["ExecutionRecord", "EvidenceRecord", "Trace"],
    validation_criteria: ["Evidence chain is correlated without unsupported inference"],
    provider_neutral: true,
  },
  {
    test_id: "AOS-GOLDEN-PATH-001",
    family: "Golden Path end-to-end conformance",
    requirement_reference: "CONFORMANCE-12",
    mode: "E2E",
    preconditions: ["All prerequisite conformance families PASS"],
    inputs: ["Authorized Golden Path request"],
    expected_behavior: ["Full governed lifecycle executes and produces auditable evidence"],
    evidence_requirements: ["Complete Golden Path evidence bundle"],
    validation_criteria: ["Authorization, failure, recovery, approval, pause/resume, result and validation are all evidenced"],
    provider_neutral: true,
  },
];
